name: "Release hooks for SRS"

on:
  push:
    tags:
      - hooks-v1*

jobs:
  docker:
    name: releases-by-docker
    runs-on: ubuntu-20.04

    steps:
      ################################################################
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      ################################################################
      # Build
      # The github.ref is, for example, refs/tags/v1.0.52
      # Generate variables like:
      #   SRS_TAG=hooks-v1.0.52
      #   SRS_MAJOR=hooks-1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| awk -F '.' '{print $1}' |sed 's/-v/-/g')
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV
      # Build SRS image
      - name: Build SRS docker image
        run: |
          echo "Release ossrs/srs-terraform:$SRS_TAG"
          docker build --tag ossrs/srs-terraform:$SRS_TAG -f hooks/Dockerfile .

      ################################################################
      # Aliyun ACR
      - name: Login Aliyun docker hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Push to Aliyun docker hub
        run: |
          docker tag ossrs/srs-terraform:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform:$SRS_TAG
          docker tag ossrs/srs-terraform:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform:$SRS_MAJOR
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform
          echo "Release ok, please see:"
          echo "  https://cr.console.aliyun.com/repository/cn-hangzhou/ossrs/srs-terraform/images"

      ################################################################
      # Tencent TCR Singapore
      - name: Login Tencent Singapore docker hub
        uses: docker/login-action@v1
        with:
          registry: sgccr.ccs.tencentyun.com
          username: "${{ secrets.TCR_USERNAME }}"
          password: "${{ secrets.TCR_PASSWORD }}"

      - name: Push to Tencent Singapore docker hub
        run: |
          docker tag ossrs/srs-terraform:$SRS_TAG sgccr.ccs.tencentyun.com/ossrs/srs-terraform:$SRS_TAG
          docker tag ossrs/srs-terraform:$SRS_TAG sgccr.ccs.tencentyun.com/ossrs/srs-terraform:$SRS_MAJOR
          docker push --all-tags sgccr.ccs.tencentyun.com/ossrs/srs-terraform
          echo "Release ok, please see:"
          echo "  https://console.cloud.tencent.com/tcr/repository/details/ccr/ossrs/srs-terraform/1"

      ################################################################
      # Tencent TCR Guangzhou
      - name: Login Tencent Guangzhou docker hub
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: "${{ secrets.TCR_USERNAME }}"
          password: "${{ secrets.TCR_PASSWORD }}"

      - name: Push to Tencent Guangzhou docker hub
        run: |
          docker tag ossrs/srs-terraform:$SRS_TAG ccr.ccs.tencentyun.com/ossrs/srs-terraform:$SRS_TAG
          docker tag ossrs/srs-terraform:$SRS_TAG ccr.ccs.tencentyun.com/ossrs/srs-terraform:$SRS_MAJOR
          docker push --all-tags ccr.ccs.tencentyun.com/ossrs/srs-terraform
          echo "Release ok, please see:"
          echo "  https://console.cloud.tencent.com/tcr/repository/details/ccr/ossrs/srs-terraform/1"
