name: "Release version management"

on:
  push:
    tags:
      - releases-v1*

jobs:
  docker:
    name: releases-by-docker
    runs-on: ubuntu-20.04

    steps:
      ################################################################
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      ################################################################
      # Build
      # The github.ref is, for example, refs/tags/v1.0.52
      # Generate variables like:
      #   SRS_TAG=releases-v1.0.52
      #   SRS_MAJOR=releases-1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| awk -F '.' '{print $1}' |sed 's/-v/-/g')
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV
      # Build SRS image
      - name: Build SRS docker image
        run: |
          echo "Release ossrs/srs-cloud:$SRS_TAG"
          docker build --tag ossrs/srs-cloud:$SRS_TAG -f ffmpeg/Dockerfile .

      ################################################################
      # Aliyun ACR
      - name: Login Aliyun docker hub
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Push to Aliyun docker hub
        run: |
          docker tag ossrs/srs-cloud:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:$SRS_TAG
          docker tag ossrs/srs-cloud:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:$SRS_MAJOR
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud
          echo "Alias srs-cloud to srs-terraform"
          docker tag ossrs/srs-cloud:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform:$SRS_TAG
          docker tag ossrs/srs-cloud:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform:$SRS_MAJOR
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform
          echo "Release ok, please see:"
          echo "  https://cr.console.aliyun.com/repository/cn-hangzhou/ossrs/srs-cloud/images"
          echo "  https://cr.console.aliyun.com/repository/cn-hangzhou/ossrs/srs-terraform/images"

      ################################################################
      # K8S
      - name: Setup KUBECONFIG for Aliyun ACK
        run: |-
          KUBECONFIG=$RUNNER_TEMP/kubeconfig_$(date +%s)
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
      # K8S for terraform versions
      - name: Release terraform versions to Aliyun ACK
        run: |-
          kubectl set image deploy/srs-terraform-deploy releases=registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:$SRS_TAG
          kubectl describe deploy/srs-terraform-deploy
