name: "Release version management"

on:
  push:
    tags:
      - releases-v1*

jobs:
  envs:
    name: envs
    steps:
      ##################################################################################################################
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # The github.ref is, for example, refs/tags/v5.0.145 or refs/tags/v5.0-r8
      # Generate variables like:
      #   SRS_TAG=nodejs-v1.0.52
      #   SRS_MAJOR=nodejs-1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| awk -F '.' '{print $1}' |sed 's/-v/-/g')
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV
    # Map a step output to a job output, see https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      SRS_TAG: ${{ env.SRS_TAG }}
      SRS_MAJOR: ${{ env.SRS_MAJOR }}
    runs-on: ubuntu-20.04

  docker:
    needs:
      - envs
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Build SRS image
      - name: Build SRS docker image
        run: |
          echo "Release ossrs/srs-cloud:$SRS_TAG"
          docker build --tag ossrs/srs-cloud:$SRS_TAG -f releases/Dockerfile .
      # Create main images for Docker
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Push to Docker hub
        run: |
          docker tag ossrs/srs-cloud:$SRS_TAG ossrs/srs-cloud:$SRS_MAJOR
          docker push --all-tags ossrs/srs-cloud
    runs-on: ubuntu-20.04

  aliyun:
    needs:
      - envs
      - docker
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      # Aliyun ACR
      - name: Login Aliyun docker hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Docker alias images for ossrs/srs-cloud
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ossrs/srs-cloud:${{ env.SRS_TAG }}
          dst: |
            registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:${{ env.SRS_TAG }}
            registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:${{ env.SRS_MAJOR }}
            registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform:${{ env.SRS_TAG }}
            registry.cn-hangzhou.aliyuncs.com/ossrs/srs-terraform:${{ env.SRS_MAJOR }}
    runs-on: ubuntu-20.04

  k8s:
    needs:
      - envs
      - aliyun
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      ################################################################
      # K8S
      - name: Setup KUBECONFIG for Aliyun ACK
        run: |-
          KUBECONFIG=$RUNNER_TEMP/kubeconfig_$(date +%s)
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
      # K8S for terraform versions
      - name: Release terraform versions to Aliyun ACK
        run: |-
          STABLE_RELEASE=platform-$(cat releases/main.go |grep 'const latest' |awk -F '"' '{print $2}')
          echo "Check stable release $STABLE_RELEASE"

          while true; do
            docker pull registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:$STABLE_RELEASE >/dev/null 2>&1 && echo "done" && break
            echo "Image $STABLE_RELEASE not ready, wait..." && sleep 5
          done

          echo "Image is ready, lets update the releases."

      ################################################################
      # Generate variables like:
      #   SRS_DROPLET_EIP=1.2.3.4
      - name: Build droplet variables
        run: |
          SRS_DROPLET_EIP=$(dig +short lh.ossrs.net)
          echo "SRS_DROPLET_EIP=$SRS_DROPLET_EIP" >> $GITHUB_ENV
      # Execute command in a ssh, because ufw limit the rate.
      - name: Restart the containers
        env:
          SEARCH_APIKEY: ${{ secrets.SEARCH_APIKEY }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SRS_DROPLET_EIP }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          port: 22
          envs: SRS_TAG,SRS_MAJOR
          timeout: 60s
          command_timeout: 30m
          script: |
            #
            #ufw allow 8101
            #
            export SRS_DROPLET_PIP=$(ifconfig eth0 |grep 'inet ' |awk '{print $2}')
            echo "SRS_DROPLET_PIP=$SRS_DROPLET_PIP"
            #
            # Restart srs-cloud releases
            for ((i=0; i < 5; i++)); do
              if [[ $(docker ps -f name=docs-cloudversion |wc -l) -eq 1 ]]; then echo "Killed"; break; fi;
              docker rm -f docs-cloudversion; sleep 0.3;
            done
            docker run -d -it --restart always --name docs-cloudversion -p 8101:9000 \
              registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:$SRS_TAG
    runs-on: ubuntu-20.04
